name: siddhartha_cli
description: Dart command line for creating new flutter project and feature architecture with clean architecture.
version: 0.0.3
repository: https://github.com/dev-siddhartha/siddhartha_cli

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  siddhartha_cli: siddhartha_cli
